version: "3.7"
services:
  server:
    build: 
      context: .
      args: 
        - NODE_ENV=production
    restart: always
    container_name: reporter-server
    command: "pm2-runtime ecosystem.config.js --env production"