version: "3.7"
services:
  server:
    build: 
      args: 
        - NODE_ENV=development
    restart: "no"
    volumes:
      - ./node_modules:/node_modules
    env_file: .env
    ports:
      - "127.0.0.1:${PORT}:1337"
