version: "3.7"
services:
  server:
    build: 
      args: 
        - NODE_ENV=development
    restart: "no"
    volumes:
      - ./node_modules:/node_modules
      - ./.tmp:/.tmp
    env_file: .env
    ports:
      - "127.0.0.1:${PORT}:1337"
    container_name: reporter-dev-server
    command: "pm2-runtime ecosystem.config.js --env development"