version: "3.7"
services:
  server:
    build: 
      context: .
      args: 
        - NODE_ENV=development
    volumes:
      - ./node_modules:/node_modules
    ports:
      - "127.0.0.1:${PORT}:1337"
    command: "node app.js"